name: CR

on:
  workflow_dispatch:
    inputs:
      start_id:
        description: start_id
        required: true
        default: "1"
      end_id:
        description: end_id
        required: true
        default: "100"
      num_threads:
        description: num_threads
        required: true
        default: "5"
    
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        run: python main.py ${{ github.event.inputs.start_id }} ${{ github.event.inputs.end_id }} ${{ github.event.inputs.num_threads }}
        env:
          PYTHONUNBUFFERED: 1

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Auto commit by GitHub Action"
          git push origin
